<?php if ($this->pageCount): ?>
    <?php
        $routeParams = [];
        if (is_array($this->params)) {
            $routeParams = $this->params;
        }
    ?>
<nav style="position:relative; float: right;">
    <ul class="pagination">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li>
                <a href="<?php echo $this->url($this->route, $routeParams + ['page' => $this->previous]); ?>" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <span aria-hidden="true">&laquo;</span>
            </li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a href="<?php echo $this->url($this->route, $routeParams + ['page' => $page]); ?>">
                    <?php echo $page; ?>
                </a></li>
            <?php else: ?>
                <li class="active">
                    <a href="#"><?php echo $page; ?> <span class="sr-only">(current)</span></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li>
                <a href="<?php echo $this->url($this->route, $routeParams + ['page' => $this->next]); ?>" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <span aria-hidden="true">&raquo;</span>
            </li>
        <?php endif; ?>
    </ul>
</nav>
<?php endif; ?>
