<div class="container">
    <div class="col-md-12">
    <button type="button" class="btn btn-default btn-lg">
        <a href="<?=$this->url('frontend')?>"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Pages</a>
    </button>
<?php if (count($this->paginator)): ?>

            <?php echo $this->paginationControl($this->paginator,
                'Sliding',
                'frontend/partials/pagination',
                array('route' => 'frontend/pages/images/pagination',
                      'params'=>array('page_id'=>$this->id))); ?>

    <?php foreach ($this->paginator as $item): ?>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Remote Path</th>
                <th>Local Path</th>
                <th>Dimension</th>
                <th>Size (bytes)</th>
                <th>Mime Type</th>
            </tr>
            </thead>
            <?php foreach ($this->paginator as $item): ?>
                <tr>
                    <td>
                        <div style="width: 450px;">
                            <a href="<?=$item['remotePath']?>" target="_blank"><?=$item['remotePath']?></a>
                        </div>
                    </td>
                    <td>
                        <div style="width: 450px;">
                            <a href="<?=$item['localPath']?>" target="_blank"><?=$item['localPath']?></a>
                        </div>
                    </td>
                    <td>
                        <div style="width: 100px;">
                            <?=$item['width']?>w <small>X</small> <?=$item['height']?>h
                        </div>
                    </td>
                    <td>
                        <?=$item['size']?>
                    </td>
                    <td>
                        <?=$item['contentType']?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php endforeach; ?>
<?php else :?>
    No images for this url were downloaded
<?php endif; ?>
</div>
